server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: blacklist
          uri: lb://BLACKLIST
          predicates:
            - Path=/api/black-list/**
          filters:
            - AutorizacionFilter
        - id: autenticacion
          uri: lb://AUTENTICACION
          predicates:
            - Path=/api/autenticacion/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true