server:
  port: 8086

spring:
  application:
    name: autenticacion
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1432;DatabaseName=autenticacion;encrypt=false;trustServerCertificate=false;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Admin123456789
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
jwt:
  secret: secret
  header: Authorization

admin-paths:
  paths:
    - uri: "/api/black-list"
      method: "POST"
    - uri: "/api/black-list"
      method: "PUT"
    - uri: "/api/black-list/{1}[1-9]+[0-9]*"
      method: "DELETE"
    - uri: "/api/black-list/{1}[1-9]+[0-9]*"
      method: "GET"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html